### ISSUE TITLE
Publish this to NPM

### ISSUE THREAD

**Issue by arunasank** [geohacker/geojson-stream-merge#17]
👋 @geohacker, opening a ticket for this, so you get notified. I think the new versions of node no longer support `process.stderr.cursorTo..`. I have:
* [x] [Pushed a fix](https://github.com/geohacker/geojson-stream-merge/pull/16)
* [x] Checked that tests pass
* [x] Merged the branch w master

Please publish this repository to NPM.

**Comment by geohacker** [comment]
@arunasank  - apologies for missing this, just getting back to the grind. Thank you very much for fixing this. I just published a minor version on npm. I've also added you as a package maintainer. 

✌️ 🙇

**Comment by arunasank** [comment]
🎉 thanks!
